name: Tests

on: [push, release]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  self-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: repository metadata
        id: repository_metadata
        uses: ./
      - run: echo "${{ steps.repository_metadata.outputs.branch }}"
