name: Tests

on: [push, release]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dockerize step
        id: dockerize
        uses: ./
        run: echo "${{ steps.dockerize.outputs.branch }}"
