name: Tests

on: [push, release]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dockerize step
        uses: ./
        id: dockerize
        run: echo ${{ steps.dockerize.outputs.branch }}
